name: Build a custom version of Wine with changes to run the latest Roblox Player

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Clone the wine-tkg-git repo
        run: git clone https://github.com/Frogging-Family/wine-tkg-git.git

      - name: Enter the just cloned directory, download the patch, and apply the patch
        run: | 
          cd wine-tkg-git
          curl https://cdn.discordapp.com/attachments/853709107495043072/876311839070375976/roblox-wine-staging.patch --output roblox-wine-staging.patch
          git apply roblox-wine-staging.patch
          
      - name: Edit the customization.cfg to download Ubuntu dependencies
        run: |
          cd wine-tkg-git/wine-tkg-git
          sed -i '/_nomakepkg_dep_resolution_distro=""/c\_nomakepkg_dep_resolution_distro="debuntu"' customization.cfg
          cat customization.cfg
      
      - name: Run apt-get update to refresh package index
        run: sudo apt-get update
      
      - name: Build wine-tkg-git
        run: |
          cd wine-tkg-git/wine-tkg-git
          ./non-makepkg-build.sh
